[tool.codespell]
count = ""
ignore-regex = '\b[A-Z]{3}\b'
ignore-words-list = "ans,asend,deques,dout,extint,hsi,iput,mis,numer,shft,technic,ure"
quiet-level = 3
skip = """
*/build*,\
./.git,\
./.gitattributes,\
./.gitignore,\
./.gitmodules,\
./LICENSE,\
./esp-idf,\
./MicroHydra,\
./MicroPython,\
./src/font,\
"""

[tool.ruff]
# Exclude third-party code from linting and formatting
extend-exclude = ["devices", "esp-idf", "MicroHydra", "MicroPython", "src/font"]
line-length = 100
target-version = "py39"
# Add micropython-specific (and viper-specific) built-in names
builtins = ["const", "micropython", "ptr", "ptr8", "ptr16", "ptr32"]

[tool.ruff.lint]
extend-select = ["C9", "PLC"]
ignore = [
  # These exclusions are borrowed from the MicroPython repo:
  "E401",
  "E402",
  "E722",
  "E731",
  "E741",
  "F401",
  "F403",
  "F405",
  # These exclusions just arent really relevant (or dont work) in MicroPython:
  "PLC1901",
  "FURB103",
  "PLW1514",
  "FBT003",
  # MH uses commented out code in the build process:
  "ERA001",
  # for now, MH takes a soft approach to quote-style.
  # You should just try to maintain consistency with surrounding code:
  "Q000",
  # Up for debate, but IMO a bit of extra space really helps with dense code blocks:
  "E303",
  # MH specifically allows the use of tabs over spaces in its code for accessibility.
  # (And spaces are allowed because they are usually the editor default):
  "D206",
  "W191",
  # This can sometimes harm performance in MP:
  "FURB136",
  "PLR1730",
  # PEP8 reccomends grouping by order-of operations
  # like: `4*6 + 12*2`
  "E226",
  # This is highly opinionated, but IMO if you are doing this,
  # you're probably trying to make the code more readable
  "E702",
]

[tool.ruff.mccabe]
# Some MicroPython code unfortunately must be somewhat complex for speed reasons.
max-complexity = 40

[tool.ruff.per-file-ignores]
# manifest.py files are evaluated with some global names pre-defined
"**/manifest.py" = ["F821"]

[tool.ruff.lint.isort]
# Use 2 lines after imports
lines-after-imports = 2